include_guard(GLOBAL)
set(SCAN_TRACKING_THICKNESS_MEASURE_V3_SDK_DIR "${CMAKE_CURRENT_SOURCE_DIR}/third_party/thickness_measure_v3" CACHE PATH "Path to ThicknessMeasureV3 SDK")
function(scan_tracking_require_thickness_measure_v3_sdk)
    if(TARGET ThicknessMeasureV3Sdk::Api)
        return()
    endif()
    set(d "${SCAN_TRACKING_THICKNESS_MEASURE_V3_SDK_DIR}")
    set(inc "${d}/include")
    set(rlib "${d}/lib/Release/ThicknessMeasureV3.lib")
    set(dlib "${d}/lib/Debug/ThicknessMeasureV3.lib")
    set(rdll "${d}/bin/Release/ThicknessMeasureV3.dll")
    set(ddll "${d}/bin/Debug/ThicknessMeasureV3.dll")
    foreach(f "${inc}/thickness_measure_v3_c_api.h" "${inc}/thickness_measure_v2_c_api.h" "${rlib}" "${rdll}")
        if(NOT EXISTS "${f}")
            message(FATAL_ERROR "ThicknessMeasureV3 SDK file not found: ${f}. Build the V3 DLL and package it under third_party/thickness_measure_v3.")
        endif()
    endforeach()
    if(NOT EXISTS "${dlib}")
        set(dlib "${rlib}")
    endif()
    if(NOT EXISTS "${ddll}")
        set(ddll "${rdll}")
    endif()
    add_library(ThicknessMeasureV3Sdk::Api SHARED IMPORTED GLOBAL)
    set_target_properties(ThicknessMeasureV3Sdk::Api PROPERTIES IMPORTED_IMPLIB_RELEASE "${rlib}" IMPORTED_IMPLIB_DEBUG "${dlib}" IMPORTED_LOCATION_RELEASE "${rdll}" IMPORTED_LOCATION_DEBUG "${ddll}" INTERFACE_INCLUDE_DIRECTORIES "${inc}")
    set_property(GLOBAL PROPERTY SCAN_TRACKING_THICKNESS_MEASURE_V3_SDK_DIR "${d}")
endfunction()
function(scan_tracking_deploy_thickness_measure_v3_runtime target)
    scan_tracking_require_thickness_measure_v3_sdk()
    get_property(d GLOBAL PROPERTY SCAN_TRACKING_THICKNESS_MEASURE_V3_SDK_DIR)
    if(EXISTS "${d}/bin/Debug/ThicknessMeasureV3.dll")
        set(_tmv3_dll "$<IF:$<CONFIG:Debug>,${d}/bin/Debug/ThicknessMeasureV3.dll,${d}/bin/Release/ThicknessMeasureV3.dll>")
    else()
        set(_tmv3_dll "${d}/bin/Release/ThicknessMeasureV3.dll")
    endif()
    if(EXISTS "${d}/bin/Debug/onnxruntime.dll")
        set(_onnxruntime_dll "$<IF:$<CONFIG:Debug>,${d}/bin/Debug/onnxruntime.dll,${d}/bin/Release/onnxruntime.dll>")
    else()
        set(_onnxruntime_dll "${d}/bin/Release/onnxruntime.dll")
    endif()
    set(_deploy_commands
        COMMAND ${CMAKE_COMMAND} -E copy_if_different "${_tmv3_dll}" "$<TARGET_FILE_DIR:${target}>"
        COMMAND ${CMAKE_COMMAND} -E copy_if_different "${_onnxruntime_dll}" "$<TARGET_FILE_DIR:${target}>"
        COMMAND ${CMAKE_COMMAND} -E make_directory "$<TARGET_FILE_DIR:${target}>/config/thickness_measure_v3"
        COMMAND ${CMAKE_COMMAND} -E copy_if_different "${d}/config/thickness_measurement.ini" "$<TARGET_FILE_DIR:${target}>/config/thickness_measure_v3/thickness_measurement.ini"
    )
    if(EXISTS "${d}/Data/pointnet_weld_seam_V7.3_good.onnx")
        list(APPEND _deploy_commands
            COMMAND ${CMAKE_COMMAND} -E make_directory "$<TARGET_FILE_DIR:${target}>/models/thickness_measure_v3"
            COMMAND ${CMAKE_COMMAND} -E copy_if_different "${d}/Data/pointnet_weld_seam_V7.3_good.onnx" "$<TARGET_FILE_DIR:${target}>/models/thickness_measure_v3/pointnet_weld_seam_V7.3_good.onnx")
    endif()
    if(EXISTS "${d}/Data")
        list(APPEND _deploy_commands
            COMMAND ${CMAKE_COMMAND} -E make_directory "$<TARGET_FILE_DIR:${target}>/config/thickness_measure_v3/Data"
            COMMAND ${CMAKE_COMMAND} -E copy_directory "${d}/Data" "$<TARGET_FILE_DIR:${target}>/config/thickness_measure_v3/Data")
    endif()
    add_custom_command(TARGET ${target} POST_BUILD ${_deploy_commands}
        COMMENT "Deploying ThicknessMeasureV3 SDK runtime")
endfunction()
